[workspace]
members = [
    "cuppies/ch32v003",
    "cpu/qingkev2a",
    "cuppies/qemu-rv32-virt",
    "xdd-proto",
    "sherbet",
]
resolver = "2"

[workspace.dependencies]
qingkev2a = { path = "cpu/qingkev2a" }
xdd-proto = { path = "xdd-proto" }
sherbet = { path = "sherbet" }
