[build]
target = "riscv32e-unknown-none-elf"

[target.riscv32e-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsherbet/layout.ld"]
runner = """
qemu-system-riscv32 -s -S -m 2048 -cpu rv32 \
-machine virt -nographic -bios none -kernel
"""
