[package]
name = "ch32v003"
description = """
ch32v003
"""
version = "0.0.0"

license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "ch32v003"
path = "main.rs"

[dependencies]
qingke-v2a = { workspace = true }
sherbet = { workspace = true }
rv32 = { workspace = true }
